### ISSUE TITLE
Undefined function or variable 'ucircdla'.

### ISSUE THREAD

**Issue by rhenryherrera** [cristian-rusu-research/SHIFT-INVARIANCE#1]
Hi Cristian, here is Reviewer 2 (Henry). 
Congrats on the excellent paper. TestECG.m works fine but TestUcirc.m doesn't find ucircdla. See below.
Running testUCirc.m

Error in TestUCirc (line 72)
[Q2, S, errorQ2, timeQ2] = ucircdla(Y, k0, L);

**Comment by cristian-rusu-research** [comment]
Hi Henry! Really sorry for the late reply, I did not see the alert from your message until now.
I corrected TestUCirc.m, the call should not be to ucircdla but to ucircdlablock.
Thanks for your interest in this work!
